### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by JKyang09** [zeek-flowmeter/zeek-flowmeter#1]
I use this script "zeek /home/flowmeter.zeek   -C -i enp4s0f0" and get "Segmentation fault"

**Comment by Jacob-Zcw** [comment]
Have you solved your problem? I have the same problem.

**Comment by JKyang09** [comment]
> Have you solved your problem? I have the same problem.

I reinstall Zeek with sourcecode and solve the problem

**Comment by Jacob-Zcw** [comment]
Are you using zeek version 4.1.1?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zeek-flowmeter/zeek-flowmeter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zeek-flowmeter/zeek-flowmeter] Segmentation fault (Issue #1)





  
Have you solved your problem? I have the same problem.
  
I reinstall Zeek with sourcecode and solve the problem
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Jacob-Zcw** [comment]
Are you using zeek4.1.1?

**Comment by Jacob-Zcw** [comment]
Are you using zeek4.1.1?

**Comment by JKyang09** [comment]
zeek4.0.4

**Comment by Jacob-Zcw** [comment]
OK, thanks!

**Comment by Jacob-Zcw** [comment]
After Zeek is installed, where do you put the FlowMeter script?
